//go:build ignore

package main

import (
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
)

func formatPromptName(filename string) string {
	name := strings.TrimSuffix(filename, ".md")
	parts := strings.Split(name, "_")
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func main() {
	const tgt = "prompt_imports.go" // 生成的文件名
	out := new(strings.Builder)
	out.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	out.WriteString(`package prompts

import (
	_ "embed" // embed prompts
	"text/template"
)

`)

	// 遍历当前目录下的所有一级子目录
	entries, err := os.ReadDir("./prompts")
	if err != nil {
		log.Fatal(err)
	}
	filenameList := []struct {
		Name    string
		Comment string
	}{}
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		// 读取文件内容第一行
		file, err := os.ReadFile("./prompts/" + e.Name())
		if err != nil {
			log.Fatal(err)
			continue
		}
		if len(file) == 0 {
			continue
		}
		firstLine := strings.TrimSpace(
			strings.TrimSuffix(
				strings.TrimPrefix(
					strings.TrimSpace(
						strings.Split(
							string(file), "\n")[0],
					),
					"{"+"{/"+"*"),
				"*"+"/}"+"}"),
		)
		name := formatPromptName(e.Name())
		filenameList = append(filenameList, struct {
			Name    string
			Comment string
		}{
			Name:    name,
			Comment: firstLine,
		})
		out.WriteString("// " + name + " " + firstLine + "\n")
		out.WriteString("//\n")
		out.WriteString("//go:embed prompts/" + e.Name() + "\n")
		out.WriteString("var " + name + " string\n\n")
	}
	for _, obj := range filenameList {
		name := obj.Name
		out.WriteString("// " + name + " " + obj.Comment + "模板\n")
		out.WriteString("var " + name + "Template *template.Template\n\n")
	}
	out.WriteString("func initTemplates(){\n")
	for _, obj := range filenameList {
		name := obj.Name
		out.WriteString("    " + name + "Template = Load(\"" + name + "\", " + name + ")\n")
	}
	out.WriteString("}\n")

	// gofmt 一下
	src, err := format.Source([]byte(out.String()))
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(tgt, src, 0644); err != nil {
		log.Fatal(err)
	}
	fmt.Println("generated", tgt)
}
