// Code generated by go generate; DO NOT EDIT.
package prompts

import (
	_ "embed" // embed prompts
	"text/template"
)

// AgentWrap Agent交互提示词
//
//go:embed prompts/agent_wrap.md
var AgentWrap string

// DefaultAgent Default agent prompt
//
//go:embed prompts/default_agent.md
var DefaultAgent string

// DeltaWrap AI response 占位符
//
//go:embed prompts/delta_wrap.md
var DeltaWrap string

// Global 全局提示词
//
//go:embed prompts/global.md
var Global string

// Init Init 指令：分析代码库并生成 AGENTS.md
//
//go:embed prompts/init.md
var Init string

// SubagentWrap Agent交互提示词
//
//go:embed prompts/subagent_wrap.md
var SubagentWrap string

// Summary Summary prompt
//
//go:embed prompts/summary.md
var Summary string

// SummaryWrap Summary
//
//go:embed prompts/summary_wrap.md
var SummaryWrap string

// Title Title generation prompt
//
//go:embed prompts/title.md
var Title string

// TitleSystem 标题生成系统提示词
//
//go:embed prompts/title_system.md
var TitleSystem string

// ToolNative Native tool calling prompt
//
//go:embed prompts/tool_native.md
var ToolNative string

// ToolPrehook 工具预调用提示词生成器
//
//go:embed prompts/tool_prehook.md
var ToolPrehook string

// ToolScopes 工具作用域
//
//go:embed prompts/tool_scopes.md
var ToolScopes string

// UserReject <| user reject last tools calling |>
//
//go:embed prompts/user_reject.md
var UserReject string

// UserWrap 用户提示词
//
//go:embed prompts/user_wrap.md
var UserWrap string

// AgentWrap Agent交互提示词模板
var AgentWrapTemplate *template.Template

// DefaultAgent Default agent prompt模板
var DefaultAgentTemplate *template.Template

// DeltaWrap AI response 占位符模板
var DeltaWrapTemplate *template.Template

// Global 全局提示词模板
var GlobalTemplate *template.Template

// Init Init 指令：分析代码库并生成 AGENTS.md模板
var InitTemplate *template.Template

// SubagentWrap Agent交互提示词模板
var SubagentWrapTemplate *template.Template

// Summary Summary prompt模板
var SummaryTemplate *template.Template

// SummaryWrap Summary模板
var SummaryWrapTemplate *template.Template

// Title Title generation prompt模板
var TitleTemplate *template.Template

// TitleSystem 标题生成系统提示词模板
var TitleSystemTemplate *template.Template

// ToolNative Native tool calling prompt模板
var ToolNativeTemplate *template.Template

// ToolPrehook 工具预调用提示词生成器模板
var ToolPrehookTemplate *template.Template

// ToolScopes 工具作用域模板
var ToolScopesTemplate *template.Template

// UserReject <| user reject last tools calling |>模板
var UserRejectTemplate *template.Template

// UserWrap 用户提示词模板
var UserWrapTemplate *template.Template

func initTemplates() {
	AgentWrapTemplate = Load("AgentWrap", AgentWrap)
	DefaultAgentTemplate = Load("DefaultAgent", DefaultAgent)
	DeltaWrapTemplate = Load("DeltaWrap", DeltaWrap)
	GlobalTemplate = Load("Global", Global)
	InitTemplate = Load("Init", Init)
	SubagentWrapTemplate = Load("SubagentWrap", SubagentWrap)
	SummaryTemplate = Load("Summary", Summary)
	SummaryWrapTemplate = Load("SummaryWrap", SummaryWrap)
	TitleTemplate = Load("Title", Title)
	TitleSystemTemplate = Load("TitleSystem", TitleSystem)
	ToolNativeTemplate = Load("ToolNative", ToolNative)
	ToolPrehookTemplate = Load("ToolPrehook", ToolPrehook)
	ToolScopesTemplate = Load("ToolScopes", ToolScopes)
	UserRejectTemplate = Load("UserReject", UserReject)
	UserWrapTemplate = Load("UserWrap", UserWrap)
}
