// Code generated by go generate; DO NOT EDIT.
package prompts

import (
	_ "embed" // embed prompts
	"text/template"
)

// DefaultAgent 默认 Agent 的提示词
//
//go:embed prompts/default_agent.md
var DefaultAgent string

// DeltaWrap AI response 占位符
//
//go:embed prompts/delta_wrap.md
var DeltaWrap string

// Global 全局提示词
//
//go:embed prompts/global.md
var Global string

// Summary 总结提示词
//
//go:embed prompts/summary.md
var Summary string

// SummaryWrap 对于不支持思考的模型的思考占位符
//
//go:embed prompts/summary_wrap.md
var SummaryWrap string

// ToolPrehook 工具预调用提示词生成器
//
//go:embed prompts/tool_prehook.md
var ToolPrehook string

// ToolResponseWrap 工具返回提示词
//
//go:embed prompts/tool_response_wrap.md
var ToolResponseWrap string

// ToolScopes 工具作用域
//
//go:embed prompts/tool_scopes.md
var ToolScopes string

// Tools 工具提示词
//
//go:embed prompts/tools.md
var Tools string

// ToolsWrap 工具占位符
//
//go:embed prompts/tools_wrap.md
var ToolsWrap string

// UserWrap 用户提示词
//
//go:embed prompts/user_wrap.md
var UserWrap string

// DefaultAgent 默认 Agent 的提示词模板
var DefaultAgentTemplate *template.Template

// DeltaWrap AI response 占位符模板
var DeltaWrapTemplate *template.Template

// Global 全局提示词模板
var GlobalTemplate *template.Template

// Summary 总结提示词模板
var SummaryTemplate *template.Template

// SummaryWrap 对于不支持思考的模型的思考占位符模板
var SummaryWrapTemplate *template.Template

// ToolPrehook 工具预调用提示词生成器模板
var ToolPrehookTemplate *template.Template

// ToolResponseWrap 工具返回提示词模板
var ToolResponseWrapTemplate *template.Template

// ToolScopes 工具作用域模板
var ToolScopesTemplate *template.Template

// Tools 工具提示词模板
var ToolsTemplate *template.Template

// ToolsWrap 工具占位符模板
var ToolsWrapTemplate *template.Template

// UserWrap 用户提示词模板
var UserWrapTemplate *template.Template

func initTemplates() {
	DefaultAgentTemplate = Load("DefaultAgent", DefaultAgent)
	DeltaWrapTemplate = Load("DeltaWrap", DeltaWrap)
	GlobalTemplate = Load("Global", Global)
	SummaryTemplate = Load("Summary", Summary)
	SummaryWrapTemplate = Load("SummaryWrap", SummaryWrap)
	ToolPrehookTemplate = Load("ToolPrehook", ToolPrehook)
	ToolResponseWrapTemplate = Load("ToolResponseWrap", ToolResponseWrap)
	ToolScopesTemplate = Load("ToolScopes", ToolScopes)
	ToolsTemplate = Load("Tools", Tools)
	ToolsWrapTemplate = Load("ToolsWrap", ToolsWrap)
	UserWrapTemplate = Load("UserWrap", UserWrap)
}
