//go:build ignore

package main

import (
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"strings"
	"time"
)

//go:generate go run gen.go

const template = `// Code generated by go generate; DO NOT EDIT.
package product

// CommitID 提交ID
const CommitID = "{commitID}"

// BuildTime 构建时间
const BuildTime uint64 = {buildTime}

// BuildNote 构建备注
const BuildNote = "{note}"
`

func main() {
	const tgt = "build.go" // 生成的文件名

	commitID := ""
	// 执行 git rev-parse HEAD 获取提交ID
	cmd := exec.Command("git", "rev-parse", "HEAD")
	out, err := cmd.Output()
	if err != nil {
		log.Fatal(err)
	}
	commitID = strings.TrimSpace(string(out))
	fmt.Println("commitID:", commitID)

	buildTime := time.Now().Unix()
	fmt.Println("buildTime:", buildTime)

	note := os.Getenv("ALKAID0_BUILD_NOTE")

	rendered := strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(template, "{commitID}", commitID), "{buildTime}", fmt.Sprintf("%d", buildTime)), "{note}", note)

	// gofmt 一下
	src, err := format.Source([]byte(rendered))
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(tgt, src, 0644); err != nil {
		log.Fatal(err)
	}
	fmt.Println("generated", tgt)
}
