//go:build ignore

package main

import (
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
)

func main() {
	const tgt = "plug_imports.go" // 生成的文件名
	out := new(strings.Builder)
	out.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	out.WriteString("package tools\n\nimport (\n")

	// 遍历当前目录下的所有一级子目录
	entries, err := os.ReadDir("./tools")
	if err != nil {
		log.Fatal(err)
	}
	for _, e := range entries {
		if !e.IsDir() || strings.HasPrefix(e.Name(), ".") {
			continue
		}
		// 构造 import 路径：module 名 + 路径
		importPath := "g" + "ithub" + ".co" + "m" + "/cxy" + "kevi" + "n/alk" + "aid0/" + "tools/tools/" + e.Name()
		out.WriteString(`	_ "` + importPath + `"` + "\n")
	}
	out.WriteString(")\n")

	// gofmt 一下
	src, err := format.Source([]byte(out.String()))
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(tgt, src, 0644); err != nil {
		log.Fatal(err)
	}
	fmt.Println("generated", tgt)
}
